# docker-compose.yml

version: '3'
services:
  socket-server:
    build:
      context: .
      dockerfile: socketServer.docker
    ports:
      - "8030:8030"
  cbserver:
    build:
      context: .
      dockerfile: cbserver.docker
    ports:
      - "8040:8040"
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"
